li=[ 'Inside Sales Associate','C++ Development (QT Creator)', 'English Programming', 'Solution Architect', 'Node.js Development', 'Flutter Development', 'Software Project Management', 'Web Development (Django)', 'Front End Development', 'Electrical Engineering', 'Mechanical Engineering (Design & 3D Printing)', 'Electronics Engineering', 'Mechanical Engineering', 'Technical Writing', 'System Administration', 'Electronics Engineering', 'Hardware Design Engineering', 'Automobile Engineering', 'Mechanical Engineering', 'AWS Cloud Management', 'Site Engineering (Civil)', 'Industrial Design Engineering', 'Site Engineering', 'Civil Engineering', 'Drone 3D Design', 'PCB Design', 'Robotics Engineering', 'PCB Design Engineering', 'Climate Change & Carbon Offsetting Engineering', 'Environmental Engineering', 'UPS Service Engineering', 'FPGA Development', 'Market Research (Environment & Climate Tech)', 'Embedded Systems', 'IT Support', 'Network Engineering', 'Food Technologist', 'Technical Support (Network Firewall)', 'Tech Assistance', 'React Native']
li1=['Intershala','IIT Bombay', 'Viacom 18 Media Private Limited', 'Pearson India Education Services Private Limited', 'HDFC Ergo General Insurance Company Limited', 'HDFC Ergo General Insurance Company Limited', 'IIT Bombay', 'IIT Bombay', 'Digital Guruji', 'Evavo Wellness & Solutions LLP', 'Maker Global', 'Pro India', 'Material Intelligence Lab', 'Bazaarvoice', 'Infraveo Technologies Private Limited', 'Techolution', 'Faclon', 'Pro India', 'Lumitech Media Incorporation', 'AegisCovenant', 'Digital Factorys', 'Techolution', 'SP Associates', 'Archelite Construction Services', 'IG Drones', 'IG Drones', 'InGen Dynamics Inc. (Part Of AH Dynamics And Robotics Private Limited)', 'Yali Mobility Private Limited', 'Pro India', 'Pro India', 'Sonodiag Solutions', 'Secure Machines Private Limited', 'Energy Alternatives India', 'Roboverse.in', 'FUEL', 'Requin Solutions Private Limited', 'HonestInnovations ForYou Private Limited', 'WiJungle - by HttpCart', 'Bootstrap Digital Solutions', 'Nioclass']
#li2=['Get hired in 7 days', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring']
#li3=['Get hired in 7 days', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring']
KI3=['Get hired in 7 days', 'Actively hiring', 'Actively hiring', 'N/A', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring', 'Actively hiring']
li9=['Internshala', 'IIT Bombay', 'Viacom 18 Media Private Limited', 'Pearson India Education Services Private Limited', 'HDFC Ergo General Insurance Company Limited', 'HDFC Ergo General Insurance Company Limited', 'IIT Bombay', 'IIT Bombay', 'Evavo Wellness & Solutions LLP', 'Maker Global', 'IG Drones', 'Faclon', 'Techolution', 'Pro India', 'Archelite Construction Services', 'Lumitech Media Incorporation', 'Digital Factorys', 'SP Associates', 'Pro India', 'Pro India', 'IG Drones', 'Pro India', 'Roboverse.in', 'Sonodiag Solutions', 'Bazaarvoice', 'Techolution', 'Yali Mobility Private Limited', 'Material Intelligence Lab', 'AegisCovenant', 'InGen Dynamics Inc. (Part Of AH Dynamics And Robotics Private Limited)', 'Energy Alternatives India', 'Secure Machines Private Limited', 'Infraveo Technologies Private Limited', 'HonestInnovations ForYou Private Limited', 'Requin Solutions Private Limited', 'FUEL', 'Bootstrap Digital Solutions', 'Nioclass', 'WiJungle - by HttpCart', 'Expertrons']
city=['Gurgaon', 'Work From Home', 'Mumbai', 'Bangalore', 'Pune', 'Pune', 'Work From Home', 'Work From Home', 'Vadodara', 'Vadodara', 'Mumbai', 'Delhi', 'Gurgaon', 'Pimpri-Chinchwad', 'Hyderabad', 'Ahmedabad', 'Bhubaneswar', 'Gurgaon', 'Bangalore', 'Delhi', 'Gurgaon', 'Kozhikode', 'Bangalore', 'Vadodara', 'Hyderabad', 'Mumbai', 'Bangalore', 'Delhi', 'Delhi', 'Gurgaon', 'Delhi', 'Bangalore', 'Hyderabad', 'Mumbai', 'Chennai', 'Delhi', 'Gurgaon', 'Bangalore', 'Pune', 'Jaipur', 'Gurgaon', 'Gurgaon', 'Gurgaon', 'Mumbai', 'Navi Mumbai', 'Mumbai', 'Turbhe']
s=['1,000-2,000 /month', '10,000-15,000 /month', '20,000 /month', '5,000 /month', '5,000 /month', '1,000-2,000 /month', '1,000-2,000 /month', '10,000 /month', '10,000 /month', '7,000-15,000 /month', '5,000 /month', '10,000 /month', '15,000-20,000 /month', '7,000 /month', '8,500 /month', '15,000 /month', '15,000 /month', '5,000 /month', '3,000 /month', '10,000 /month', '15,000 /month', '12,000 /month', '10,000 /month', '8,500 /month', '5,000 /month', '6,000-10,000 /month', '19,000 /month', '20,000 /month', '6,000-8,000 /month', '6,000 /month', '5,000 /month', '9,000 /month', '8,000 /month', '8,000-10,000 /month', '6,000-8,000 /month', '20,000-25,000 /month', '25,000-30,000 /month', '12,000-17,000 /month', '12,000-18,000 /month']
print(len(s))
print(len(city))
print(len(li))
print(len(li9))

print(len(KI3))
for i in range(len(KI3)):
    print(li[i],li9[i],KI3[i])