import spacy
nlp = spacy.load("en_core_web_sm")
list_of_strings=['Roorkee23February2023IndianInstituteofTechnologyIITRoorkeeanInstituteofNationalImportancehasannouncedtoopenapplicationportalforSPARKprogramaninstitutefundedSummerInternshipsprogrammesforuniversitystudentssoon', 'SomeofthesalientfeaturesofSPARKprogramincludes', 'StipendofRs2500week', 'Onlinehasslefreeapplicationprocess', 'Studentsworkonfocussedprojectsadvertisedatthetimeofapplication', 'Regularprogressreviewsandpostersessionswithawardsforbestposters', 'Startingfrom2018IITRoorkeeoffersinstitutefundedwithastipendofRs2500weekandprojectfundedsummerinternshipsundertheSPARKprogramTheobjectiveofthisprogrammeistoattractandnurturetalentedundergraduatestudentsacrossthecountryLastyearwith15000applications120offersweremade', 'EligibilityConditionsStudentswhoarecurrentlyenrolledandhavecompletedatleasttwosemestersoftheundergraduatedegreeBArchBEBTechMScinarelevantdisciplinefromanyinstituteinIndia', 'FollowingminimumCGPAcriterionwillapply', 'CGPA75forIITsIISc', 'CGPA80forNITsIISERsNISERIIESTUMDAECBS', 'CGPA85forstudentsofotherinstitutes', 'ForfurtherdetailsabouteligibilityconditionshowtoapplyandotherdetailsthecandidatesshouldrefertheSPARKPageofIITRoorkee', 'httpssparkiitracin']


for string in list_of_strings:
    doc = nlp(string)
    for entity in doc.ents:
        if entity.label_ == "ORG":
            print(entity.text)